"""Manually authored portrait controls from subject-labelled public images.

These are artistic interpretations, not measurements or biometric identity
verification. Editorial claims attached to reference pages are not used. Photos
are neither sampled into textures nor bundled or downloaded by the game.
"""
from copy import deepcopy

STUDIES = {'tophiachu': {'status': 'source_attributed_study',
               'sources': ['https://knowyourmeme.com/memes/people/tophiachu-tiktok-lolcow',
                           'https://tenor.com/view/tophia-tophiachu-28-smirk-devious-gif-11870591702852091627'],
               'width': 0.167,
               'height': 0.337,
               'chin': 1.519,
               'jaw': 1.0,
               'cheek': 1.035,
               'temple': 0.985,
               'depth': 0.145,
               'eye_spread': 0.061,
               'eye_width': 0.0275,
               'eye_open': 0.009,
               'eye_level': 0.558,
               'hood': 0.004,
               'nose_width': 0.032,
               'nose_projection': 0.037,
               'nose_level': 0.405,
               'bridge': 0.018,
               'mouth_width': 0.052,
               'lip': 0.0073,
               'mouth_level': 0.235,
               'brow': 0.006,
               'hair': 'tied_curls',
               'glasses': 'none',
               'beard': 'none',
               'band': True,
               'skin': (0.62, 0.47, 0.35),
               'hair_color': (0.075, 0.058, 0.045),
               'gear': (0.26, 0.25, 0.29),
               'trim': (0.34, 0.26, 0.3),
               'iris': (0.22, 0.14, 0.09),
               'neck_fill': 1.1,
               'shirt': True,
               'band_color': (0.68, 0.54, 0.16),
               'crease': 0.45,
               'hair_volume': 0.026},
 'novaonline': {'status': 'source_attributed_study',
                'sources': ['https://knowyourmeme.com/memes/people/nova-online-tiktok-lolcow',
                            'https://www.youtube.com/watch?v=ZGQoShXI2Ho'],
                'width': 0.165,
                'height': 0.35,
                'chin': 1.516,
                'jaw': 1.035,
                'cheek': 1.04,
                'temple': 0.99,
                'depth': 0.146,
                'eye_spread': 0.061,
                'eye_width': 0.029,
                'eye_open': 0.0094,
                'eye_level': 0.57,
                'hood': 0.0025,
                'nose_width': 0.026,
                'nose_projection': 0.043,
                'nose_level': 0.42,
                'bridge': 0.022,
                'mouth_width': 0.046,
                'lip': 0.0051,
                'mouth_level': 0.258,
                'brow': 0.0045,
                'hair': 'parted_shoulder',
                'glasses': 'rectangle',
                'beard': 'chin_shadow',
                'band': False,
                'skin': (0.82, 0.68, 0.6),
                'hair_color': (0.22, 0.15, 0.11),
                'gear': (0.22, 0.17, 0.32),
                'trim': (0.27, 0.23, 0.35),
                'iris': (0.26, 0.24, 0.19),
                'neck_fill': 1.16,
                'shirt': True,
                'crease': 0.45},
 'cyraxx': {'status': 'source_attributed_study',
            'sources': ['https://tenor.com/view/cyraxx-chance-wilkins-psyraxx-43-gif-7870491556437349690'],
            'width': 0.134,
            'height': 0.355,
            'chin': 1.523,
            'jaw': 0.93,
            'cheek': 0.97,
            'temple': 1.0,
            'depth': 0.134,
            'eye_spread': 0.054,
            'eye_width': 0.026,
            'eye_open': 0.0093,
            'eye_level': 0.576,
            'hood': 0.003,
            'nose_width': 0.022,
            'nose_projection': 0.052,
            'nose_level': 0.408,
            'bridge': 0.026,
            'mouth_width': 0.043,
            'lip': 0.0038,
            'mouth_level': 0.24,
            'brow': 0.004,
            'hair': 'balding_fringe',
            'glasses': 'none',
            'beard': 'long_beard',
            'band': False,
            'skin': (0.79, 0.66, 0.55),
            'hair_color': (0.26, 0.2, 0.14),
            'gear': (0.095, 0.1, 0.1),
            'trim': (0.35, 0.32, 0.19),
            'iris': (0.28, 0.3, 0.25),
            'neck_fill': 0.85,
            'shirt': True,
            'beard_length': 0.046,
            'crease': 0.65,
            'beard_color': (0.2, 0.135, 0.09)},
 'candy_rooks': {'status': 'source_attributed_study',
                 'sources': ['https://open.spotify.com/episode/1cdZ9Rc2SO3ukrnMlHwerB'],
                 'width': 0.169,
                 'height': 0.349,
                 'chin': 1.516,
                 'jaw': 1.03,
                 'cheek': 1.05,
                 'temple': 1.0,
                 'depth': 0.148,
                 'eye_spread': 0.062,
                 'eye_width': 0.0285,
                 'eye_open': 0.011,
                 'eye_level': 0.57,
                 'hood': 0.003,
                 'nose_width': 0.034,
                 'nose_projection': 0.032,
                 'nose_level': 0.416,
                 'bridge': 0.015,
                 'mouth_width': 0.052,
                 'lip': 0.0083,
                 'mouth_level': 0.257,
                 'brow': 0.0048,
                 'hair': 'short_coils',
                 'glasses': 'none',
                 'beard': 'none',
                 'band': False,
                 'skin': (0.5, 0.34, 0.27),
                 'hair_color': (0.065, 0.049, 0.039),
                 'gear': (0.16, 0.12, 0.135),
                 'trim': (0.27, 0.2, 0.23),
                 'iris': (0.13, 0.095, 0.065),
                 'neck_fill': 1.16,
                 'shirt': True,
                 'crease': 0.55},
 'andy_ditch': {'status': 'source_attributed_study',
                'sources': ['https://tenor.com/view/andrew-ditch-ditch-poopsquatch-andy-ditch-andy-gif-16852068161994619749'],
                'width': 0.173,
                'height': 0.356,
                'chin': 1.505,
                'jaw': 1.05,
                'cheek': 1.05,
                'temple': 0.99,
                'depth': 0.152,
                'eye_spread': 0.063,
                'eye_width': 0.028,
                'eye_open': 0.009,
                'eye_level': 0.602,
                'hood': 0.004,
                'nose_width': 0.028,
                'nose_projection': 0.047,
                'nose_level': 0.436,
                'bridge': 0.024,
                'mouth_width': 0.048,
                'lip': 0.0037,
                'mouth_level': 0.278,
                'brow': 0.0035,
                'hair': 'close_bald',
                'glasses': 'rectangle',
                'beard': 'short_stubble',
                'band': False,
                'skin': (0.81, 0.66, 0.6),
                'hair_color': (0.2, 0.145, 0.12),
                'gear': (0.67, 0.34, 0.13),
                'trim': (0.34, 0.25, 0.19),
                'iris': (0.26, 0.29, 0.27),
                'neck_fill': 1.28,
                'shirt': True,
                'crease': 0.8},
 'daniel_larson': {'status': 'source_attributed_study',
                   'sources': ['https://knowyourmeme.com/photos/2345829-daniel-larson',
                               'https://tenor.com/view/daniel-larson-danderson-daniellarson-daniel-larson-gif-14768455700226943549'],
                   'width': 0.132,
                   'height': 0.355,
                   'chin': 1.519,
                   'jaw': 0.86,
                   'cheek': 0.98,
                   'temple': 1.01,
                   'depth': 0.131,
                   'eye_spread': 0.056,
                   'eye_width': 0.027,
                   'eye_open': 0.01,
                   'eye_level': 0.594,
                   'hood': 0.0025,
                   'nose_width': 0.02,
                   'nose_projection': 0.067,
                   'nose_level': 0.398,
                   'bridge': 0.033,
                   'mouth_width': 0.047,
                   'lip': 0.0035,
                   'mouth_level': 0.245,
                   'brow': 0.004,
                   'hair': 'rough_crop',
                   'glasses': 'none',
                   'beard': 'light_stubble',
                   'band': False,
                   'skin': (0.76, 0.56, 0.44),
                   'hair_color': (0.19, 0.125, 0.085),
                   'gear': (0.12, 0.29, 0.52),
                   'trim': (0.4, 0.28, 0.19),
                   'iris': (0.28, 0.43, 0.48),
                   'neck_fill': 0.85,
                   'shirt': True,
                   'crease': 1.0},
 'referee_cobra': {'status': 'source_attributed_study',
                   'sources': ['https://www.indy100.com/news/kingcobrajfs-youtuber-musician-cause-of-death-investigation-explained',
                               'https://cowboystatedaily.com/2025/09/13/how-a-bullied-casper-kid-went-viral-as-the-internets-gothic-kingcobra/'],
                   'width': 0.142,
                   'height': 0.365,
                   'chin': 1.512,
                   'jaw': 0.94,
                   'cheek': 0.96,
                   'temple': 1.0,
                   'depth': 0.139,
                   'eye_spread': 0.056,
                   'eye_width': 0.0275,
                   'eye_open': 0.0094,
                   'eye_level': 0.59,
                   'hood': 0.003,
                   'nose_width': 0.022,
                   'nose_projection': 0.053,
                   'nose_level': 0.414,
                   'bridge': 0.027,
                   'mouth_width': 0.047,
                   'lip': 0.0035,
                   'mouth_level': 0.255,
                   'brow': 0.0045,
                   'hair': 'receding_long',
                   'glasses': 'rectangle',
                   'beard': 'goatee',
                   'band': False,
                   'skin': (0.78, 0.65, 0.57),
                   'hair_color': (0.14, 0.1, 0.075),
                   'gear': (0.75, 0.76, 0.75),
                   'trim': (0.08, 0.085, 0.09),
                   'iris': (0.26, 0.29, 0.25),
                   'neck_fill': 0.9,
                   'shirt': True,
                   'beard_length': 0.04,
                   'crease': 0.6,
                   'black_bandana': True,
                   'frame_width': 0.046,
                   'frame_height': 0.023},
 'jupiter_the_hybrid': {'status': 'source_attributed_study',
                        'sources': ['https://open.spotify.com/episode/2EpxP1PWU3fHsPguvZ9cOZ'],
                        'coverage': 'Subject-labelled cover; right closed-mouth portrait; side '
                                    'view still needed.',
                        'width': 0.165,
                        'height': 0.349,
                        'chin': 1.516,
                        'jaw': 1.02,
                        'cheek': 1.025,
                        'temple': 1.0,
                        'depth': 0.144,
                        'eye_spread': 0.06,
                        'eye_width': 0.0285,
                        'eye_open': 0.0112,
                        'eye_level': 0.574,
                        'hood': 0.0025,
                        'nose_width': 0.029,
                        'nose_projection': 0.043,
                        'nose_level': 0.416,
                        'bridge': 0.02,
                        'mouth_width': 0.049,
                        'lip': 0.0061,
                        'mouth_level': 0.252,
                        'brow': 0.0095,
                        'hair': 'wavy_crop',
                        'glasses': 'none',
                        'beard': 'short_stubble',
                        'band': False,
                        'skin': (0.76, 0.61, 0.52),
                        'hair_color': (0.072, 0.054, 0.044),
                        'gear': (0.17, 0.16, 0.19),
                        'trim': (0.25, 0.23, 0.27),
                        'iris': (0.24, 0.17, 0.105),
                        'neck_fill': 1.14,
                        'shirt': True,
                        'crease': 0.5},
 'anacondasin': {'status': 'source_attributed_study',
                 'sources': ['https://open.spotify.com/episode/3k0IOy5dBTIbC7HTutG0en'],
                 'coverage': 'Subject-labelled cover; central backwards-cap portrait; side view '
                             'still needed.',
                 'width': 0.163,
                 'height': 0.353,
                 'chin': 1.515,
                 'jaw': 0.97,
                 'cheek': 1.01,
                 'temple': 0.98,
                 'depth': 0.145,
                 'eye_spread': 0.059,
                 'eye_width': 0.0285,
                 'eye_open': 0.011,
                 'eye_level': 0.58,
                 'hood': 0.002,
                 'nose_width': 0.026,
                 'nose_projection': 0.047,
                 'nose_level': 0.422,
                 'bridge': 0.024,
                 'mouth_width': 0.05,
                 'lip': 0.006,
                 'mouth_level': 0.255,
                 'brow': 0.0055,
                 'hair': 'cap_waves',
                 'glasses': 'rectangle',
                 'beard': 'none',
                 'band': False,
                 'skin': (0.8, 0.64, 0.55),
                 'hair_color': (0.26, 0.18, 0.12),
                 'gear': (0.16, 0.15, 0.14),
                 'trim': (0.28, 0.24, 0.19),
                 'iris': (0.32, 0.29, 0.22),
                 'neck_fill': 1.03,
                 'shirt': True,
                 'crease': 0.5,
                 'frame_width': 0.049,
                 'frame_height': 0.025}}

def apply_visual_profiles(profiles):
    """Override palettes, not rig dimensions, collision, or game statistics."""
    result=deepcopy(profiles)
    for key,profile in result.items():
        study=STUDIES[key]
        if study['status'] != 'source_attributed_study':continue
        for field in ['skin','hair_color','gear','trim']:
            profile[field]=study[field]
    return result
